version: '3.9'

services:

  db:
    container_name: db
    hostname: db
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready -U ${DATABASE_USER:-pguser} -d ${DATABASE_NAME:-huntag}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:-pguser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-pgpwd}
      POSTGRES_DB: ${DATABASE_NAME:-huntag}
    restart: always
    networks:
      - default

  bot:
    container_name: bot
    hostname: bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      DATABASE_USER: ${DATABASE_USER:-pguser}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-pgpwd}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-huntag}
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge
