version: '3.9'

services:

  db:
    container_name: db
    hostname: db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    expose:
      - 9000
    restart: always
    volumes:
      - ./db/:/root/db/
    networks:
      - default

  bot:
    container_name: bot
    hostname: bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      DATABASE_USER: ${DATABASE_USER:-pguser}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-pgpwd}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-intelligence}
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge
